### ISSUE TITLE
Order search results

### ISSUE THREAD

**Issue by Olli** [atom/atom-package-downloader#2]
Hi,
I think it's a good idea if it's possible to order the search results by downloads or "stars". 
That's a feature request :)

**Comment by Arcanemagus** [comment]
This belongs over on [atom/settings-view](https://github.com/atom/settings-view/), this repo is a utility that is used for research into the current practices of Atom packages.

**Comment by lee-dohm** [comment]
@Olli As @Arcanemagus points out, this is probably the wrong repo. You're looking for atom/settings-view or atom/atom.io depending on whether you mean inside the Settings View or on the website.
